version: "3.8"

services:
  backup:
    image: oven/bun:latest
    restart: unless-stopped
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: bun run index.ts
    environment:
      # Telegram Configuration
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_ADMIN_CHAT_IDS=${BOT_ADMIN_CHAT_IDS}

      # S3 Configuration
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}

      # Backup Configuration
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS}